services:
  postgres:
    image: postgres:16-alpine
    container_name: simvex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: simvex
      POSTGRES_USER: dosacha
      POSTGRES_PASSWORD: dosacha
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dosacha -d simvex"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - simvex_pg_data:/var/lib/postgresql/data

volumes:
  simvex_pg_data:
